#!/bin/bash

echo "Enter the Subnet:"
read Subnet

if [ "$Subnet" == "" ]
then
	echo "Enter the Subnet:"
	echo "Syntax example = ./ping_sweep.sh 10.1.68"
else
	for IP in $(seq 1 254); do
		ping -c 1 $Subnet.$IP | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" > discovered IPs_Zaid.txt &
done
fi



discoveredIPs.txt | sort > discoveredIPs.txt

nmap -T4 -sV -A -iL discoveredIPs.txt -oN PortScanIPs.txt --append-output

exit
